"$schema" = "./node_modules/wrangler/config-schema.json"
name = "petpet-web"
compatibility_date = "2026-02-10"
compatibility_flags = [ "nodejs_compat" ]
main = "./dist/_worker.js/index.js"
send_metrics=false

[assets]
binding = "ASSETS"
directory = "./dist"
not_found_handling = "404-page"

[observability]
enabled = true

[placement]
mode = "smart"