"$schema" = "./node_modules/wrangler/config-schema.json"
name = "petpet-web"
compatibility_date = "2026-02-10"
compatibility_flags = [ "nodejs_compat" ]
main = "./dist/_worker.js/index.js"
send_metrics=false

[assets]
binding = "ASSETS"
directory = "./dist/app"
not_found_handling = "404-page"

[observability]
enabled = true

[placement]
mode = "smart"

[[vpc_services]]
binding = "VPC_SERVICE"
service_id = "019c4aaa-ce51-7883-92a8-eb92da796c67" # Replace with your VPC service ID